language: android
sudo: required
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk8

cache:
  directories:

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # python
    - $HOME/.cache/pip/

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-19
    - android-24
    - sys-img-armeabi-v7a-android-19

before_install:
  - sudo pip install Pillow
  - sdkmanager tools
  - sdkmanager 'system-images;android-24;default;x86'

before_script:
  - echo no | avdmanager create avd --force -n testCompactCalendarEmulator -k "system-images;android-24;default;x86"
  - mksdcard -l sdcard 100M sdcard
  - $ANDROID_HOME/emulator/emulator -avd testCompactCalendarEmulator -no-audio -no-window -sdcard sdcard &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew verifyMode screenshotTests -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms1024m -Xmx1024m" -Dorg.gradle.daemon=false
  - ./gradlew test

